site_name: hololinked
site_url: https://hololinked.readthedocs.io
repo_url: https://github.com/VigneshVSV/hololinked
repo_name: hololinked
edit_uri: https://github.com/hololinked-dev/docs-v2/edit/main/docs/


nav:
  # landing page
  - Home: 
    - Introduction: index.md
    - Installation: introduction/installation.md
    - Resources: introduction/resources.md
  # textbook like How To tutorials
  - How To: 
    - Expose Python Objects: howto/articles/servers.md
    - Connect to Things with Clients: howto/articles/clients.md
    - Properties in Depth: 
      - Properties: howto/articles/properties/index.md
      - Default Arguments: howto/articles/properties/arguments.md
      - Extending: howto/articles/properties/extending.md
    - Using Actions: howto/articles/actions.md
    - Using Events: howto/articles/events.md
    - Using State Machine: howto/articles/state-machine.md
    - Configuring Thing Class: 
      - Thing: howto/articles/thing/index.md
    - Using Different Protocols:
      - Object Proxy: howto/articles/object-proxy.md
    - Serialization: howto/articles/serialization.md
  # API Reference
  - API Reference:
    - Thing:
      - Thing: api-reference/thing/index.md
      - RemoteAccessHandler: api-reference/thing/logger.md
      - StateMachine: api-reference/thing/state-machine.md
      - Bases & Meta:
        - Parameterized: api-reference/thing/bases/parameterized.md
        - RemoteInvokable: api-reference/thing/bases/remote-invokable.md
        - EventSource: api-reference/thing/bases/event-source.md
        - ThingMeta: api-reference/thing/thing-meta.md
    - Property: api-reference/property/index.md
    - Actions: 
      - action: api-reference/action/index.md
      - Bases: api-reference/action/bases/index.md
    - Events:
      - Event: api-reference/events/index.md
      - EventDispatcher: api-reference/events/event-dispatcher.md
    - Clients:
      - Abstractions: 
        - ConsumedThingAction: api-reference/clients/bases/cta.md
        - ConsumedThingProperty: api-reference/clients/bases/ctp.md
        - ConsumedThingEvent: api-reference/clients/bases/cte.md
    - Protocols:
      - HTTP:
        - HTTPServer: api-reference/protocols/http/http-server.md
      - ZMQ: 
        - Message: api-reference/protocols/zmq/message.md
        - Brokers:
          - BaseZMQ: api-reference/protocols/zmq/brokers/base-zmq.md
          - AsyncZMQServer: api-reference/protocols/zmq/brokers/async-zmq-server.md
          - SyncZMQClient: api-reference/protocols/zmq/brokers/sync-zmq-client.md
          - AsyncZMQClient: api-reference/protocols/zmq/brokers/async-zmq-client.md
          - MessageMappedClientPool: api-reference/protocols/zmq/brokers/message-mapped-zmq-client-pool.md
        - RPC Server: api-reference/protocols/zmq/rpc-server.md
    
    - Serializers:
      - Serializers: api-reference/serializers/index.md
     
  # Examples
  - Examples:
    - Energy Meter: examples/energy-meter.md
    - Linear Stage: examples/linear-stage.md
    - Oscilloscope: examples/oscilloscope.md
    - Camera: examples/camera.md
    - ADC in Raspberry Pi: examples/adc.md
  # - Blog:
  #   - blog/index.md


theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: yellow

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: brown
      accent: orange

  icon:
    repo: fontawesome/brands/github
    
  features:
    # editing the page
    - content.action.edit
    - content.action.view
    # search
    - search.suggest
    - search.highlight
    - search.share
    # code
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # headers
    - announce.dismiss
    # footer 
    - navigation.footer
    # navigation
    - navigation.tabs
    - navigation.path
    - navigation.prune 
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.top

  font:
    text: Segoe UI
  
   
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-authors
  - search
  - macros
  # - blog
  # - social
  - mkdocstrings:
      handlers:
        python: 
          options:
            # code base and inheritance
            allow_inspection: true
            show_bases: true
            show_inheritance_diagram: true
            # headings
            show_root_heading: true
            parameter_headings: true
            heading_level: 1
            show_category_heading: true
            # docstrings style 
            docstring_style: numpy
            group_by_category: true
        
                  
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - toc:
      toc_depth: 3
  

extra:
  social:
    - icon: fontawesome/solid/book
      link: https://github.com/hololinked-dev/examples
      name: examples repository
    - icon: fontawesome/solid/table-list
      link: https://hololinked.dev/ 
      name: directory of device implementations
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/hololinked/
      name: pypi
    - icon: fontawesome/brands/python
      link: https://anaconda.org/conda-forge/hololinked
      name: anaconda
    - icon: fontawesome/brands/git
      link: https://github.com/hololinked-dev/docs
      name: source code for docs
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/kEz87zqQXh
      name: discord group
    - icon: fontawesome/solid/envelope
      link: mailto:admin@hololinked.dev?subject=Inquiry/Feedback%20about%20hololinked"
      name: email
    - icon: fontawesome/solid/globe
      link: https://hololinked.dev/
      name: project website containing non-documentation resources
    - icon: fontawesome/solid/circle-dollar-to-slot 
      link: https://github.com/sponsors/VigneshVSV
      name: sponsor

  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - reject
      - accept
      - manage 


extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css


extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js