site_name: hololinked
site_url: https://hololinked.readthedocs.io
repo_url: https://github.com/VigneshVSV/hololinked
repo_name: hololinked
edit_uri: https://github.com/hololinked-dev/docs-v2/edit/main/docs/


theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: yellow

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: brown
      accent: orange

  icon:
    repo: fontawesome/brands/github
    
  features:
    # editing the page
    - content.action.edit
    - content.action.view
    # search
    - search.suggest
    - search.highlight
    - search.share
    # code
    - content.code.copy
    - content.code.select
    # headers
    - announce.dismiss
    # footer 
    - navigation.footer
    # navigation
    - navigation.tabs
    - navigation.path
    - navigation.prune 
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress

  font:
    text: Roboto


plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      
  - git-authors:

  - search:


markdown_extensions:
  # - attr_list
  # - md_in_html
  - pymdownx.superfences
  # - pymdownx.tabbed
  - pymdownx.snippets

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/kEz87zqQXh


extra_css:
  - stylesheets/extra.css